<?php
/**
 * file: AgentModel.class.php
 * desc: 平台控制器
 * user: liujx
 * date: 2015-11-30
 */
class ServerModel extends CommModel
{
    public $arrEditTh    = array();
    public $strLike      = 'serverName';

    // 表头字段
    public $arrShowTh = array(
        array('title' => '服务器ID', 'name' => 'id', 'sort' => true, 'search' => array('type' => 'text')),
        array('title' => '项目ID', 'name' => 'projectId'),
        array('title' => '平台商ID', 'name' => 'agentid', 'sort' => true, 'search' => array('type' => 'select')),
        array('title' => '服务器名称', 'name' => 'serverName', 'sort' => true),
        array('title' => '推荐服', 'name' => 'recommend', 'search' => array('type' => 'select')),
        array('title' => '状态', 'name' => 'status', 'search' => array('type' => 'select')),
        array('title' => '排序', 'name' => 'sort', 'sort' => true),
        array('title' => '开服时间', 'name' => 'open_time', 'sort' => true),
    );

    // 添加数据
    public $arrAddTh = array(
        'id'         => array('label' => '服务器ID', 'other' => array('required' => true, 'number' => true)),
        'projectId'  => array('label' => '项目ID', 'value' => 1, 'other' => array('required' => true, 'number' => true)),
        'agentid'    => array('label' => '平台ID', 'type' => 'select', 'other' => array('required' => true, 'number' => true)),
        'serverName' => array('label' => '服务器名称', 'other' => array('required' => true, 'rangelength' => '[2, 20]')),
        'mongoHost'  => array('label' => 'Mongo地址', 'other' => array('required' => true, 'rangelength' => '[2, 50]')),
        'mongoPort'  => array('label' => 'Mongo端口', 'other' => array('required' => true, 'number' => true, 'value' => 27017)),
        'mongoName'  => array('label' => 'Mongo库名', 'other' => array('required' => true, 'rangelength' => '[2, 50]')),
        'sort'       => array('label' => '排序', 'value' => 100, 'other' => array('required' => true, 'number' => true)),
        'recommend'  => array('label' => '推荐服', 'type' => 'radio', 'checked' => 0, 'other' => array('required' => true)),
        'status'     => array('label' => '服务器状态', 'type' => 'radio', 'checked' => 1, 'other' => array('required' => true)),
    );

    // 导入数据表单信息
    public $arrImport = array(
        'agentid'     => array('label' => '平台ID', 'type' => 'select', 'other' => array('required' => true, 'number' => true, 'class' => 'm-agentId')),
        'mysqlHost'   => array('label' => 'mySQL地址', 'other' => array('required' => true)),
        'mysqlPort'   => array('label' => 'mySQL端口', 'other' => array('required' => true, 'number' => true)),
        'mysqlName'   => array('label' => 'mySQL库名', 'other' => array('required' => true)),
        'mysqlUser'   => array('label' => 'mySQL用户名', 'other' => array('required' => true)),
        'mysqlPass'   => array('label' => 'mySQL密码', 'other' => array('required' => true)),
        'serverStart' => array('label' => '开始服', 'other' => array('number' => true)),
        'serverEnd'   => array('label' => '结束服', 'other' => array('number' => true)),
        'isUser'      => array('label' => '导入用户数据', 'type' => 'radio', 'value' => array('否', '是'), 'checked' => 1, 'other' => array('required' => true)),
    );

    // 验证数据
    protected $_validate = array(
        array('id', 'require', '服务器ID不能为空', 1),
        array('id', 'number', '服务器ID必须为一个数字', 1),
        array('projectId', 'require', '项目ID不能为空', 1),
        array('projectId', 'number', '项目ID必须为一个数字', 1),
        array('agentid', 'require', '平台ID不能为空', 1),
        array('agentid', 'number', '平台ID必须为一个数字', 1),
        array('serverName', 'require', '服务器名称不能为空', 1),
        array('serverName', '/\S{2,20}/', '服务器名称需要为2到20位字符', 1),
        array('recommend', 'number', '推荐信息错误', 1),
        array('sort', 'number', '排序必须为一个数字', 1),
        array('status', 'number', '服务器状态错误', 1),
        array('mongoHost', 'require', 'Mongo地址不能为空', 1),
        array('mongoPort', 'require', 'Mongo端口不能为空', 1),
        array('mongoPort', 'number', 'Mongo端口需要为一个数字', 1),
        array('mongoName', 'require', 'Mongo库名不能为空', 1),
    );

    // 显示详情
    public $attribute = array(
        'id'         => '服务器ID',
        'projectId'  => '项目ID',
        'agentid'    => '平台商ID',
        'serverName' => '服务器名称',
        'recommend'  => '推荐服',
        'status'     => '服务器状态',
        'sort'       => '排序',
        'mongoHost'  => 'Mongo地址',
        'mongoPort'  => 'Mongo端口',
        'mongoName'  => 'Mongo库名',
        'open_time'  => '开服时间',
        'createTime' => '创建时间',
        'createId'   => '创建用户',
        'updateTime' => '修改时间',
        'updateId'   => '修改用户',
        'unique'     => '唯一ID',
    );

    // 添加之前的处理
    public function _before_insert(&$data, $options)
    {
        $data['open_time'] = time();
        return parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
    }
}